version: '3.7'

services:
  RedisApplication:
    image: leoperelygin/redis1
    ports:
    - 8082:8080
  RedisApplication1:
    image: leoperelygin/redis1
    ports:
    - 8085:8080
  nginx:
    image: nginx:1.17.2-alpine
    ports:
    - 81:80
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - RedisApplication
    - RedisApplication1
  redis:
    image: 'bitnami/redis:latest'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
    - ./storage/redis/data:/data
    ports:
    - 6379:6379
